### ISSUE TITLE
Symfony and FOS

### ISSUE THREAD

**Issue by Barno** [expertcoder/SwiftmailerSendGridBundle#13]
Hi, Im using FosUserBundle and SendGrid

I'm trying your bundle but I have few problems.
If i try to send email via HTTP ( Curl ) I don't have any problem ( The sendgrid_api_key is ok)
In symfony, I followed all steps but the emails aren't send

In var/logs/dev.log I Don't have any logs

My config.yml

```
swiftmailer:
    transport: expertcoder_swift_mailer.send_grid.transport

expert_coder_swiftmailer_send_grid:
    api_key: %sendgrid_api_key%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
```

**Comment by moux2003** [comment]
which symfony and bundle version are you using ?

**Comment by Barno** [comment]
` "require": {
        "php": ">=5.5.9",
        "friendsofsymfony/user-bundle": "~2.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "expertcoder/swiftmailer-send-grid-bundle": "~1.0",
    },`

in composer update I can see

  - Installing sendgrid/php-http-client (3.9.6): 
  - Installing sendgrid/sendgrid (5.6.2): 
  - Installing expertcoder/swiftmailer-send-grid-bundle (1.1.0): 

Can I See any logs?

**Comment by moux2003** [comment]
I'm sorry but I have no issues with your installation to send emails on a new project.
Maybe you should review your configuration of FOS User Bundle.
If this can help here is my config file for testing purpose:
```yaml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: expertcoder_swift_mailer.send_grid.transport
    spool: { type: memory }

expert_coder_swiftmailer_send_grid:
    api_key: '%sendgrid_api_key%'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        noreply@example.com
        sender_name:    Demo App
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            template:   '@FOSUser/Registration/email.txt.twig'
            enabled: true
```

Please ensure your services.yaml file also have:
````yaml
swiftmailer.mailer.transport.expertcoder_swift_mailer.send_grid.transport:
      alias: expertcoder_swift_mailer.send_grid.transport
```

Good luck !
